import json
from typing import Optional
from models import Talk


# Real PyCon US 2026 schedule — Long Beach, CA
# Friday May 15 = conference day 1, Saturday May 16 = day 2, Sunday May 17 = day 3
SEED_TALKS = [
    # ── FRIDAY MAY 15 ──────────────────────────────────────────────
    {
        "id": "fri-1",
        "title": "Keynote — Lin Qiao",
        "speaker": "Lin Qiao",
        "track": "Keynote",
        "day": "Friday",
        "time": "9:45 AM",
        "room": "Pacific Ballroom - Arena",
        "duration_minutes": 45,
        "description": "Opening keynote of PyCon US 2026 main conference by Lin Qiao.",
        "tags": ["keynote", "plenary"],
        "difficulty": "all",
    },
    {
        "id": "fri-2",
        "title": "Mind the gap! Why static typing requires more than just adding annotations",
        "speaker": "Jia Chen, Steven Troxler",
        "track": "Core Python",
        "day": "Friday",
        "time": "11:00 AM",
        "room": "Room 103ABC",
        "duration_minutes": 45,
        "description": "Why adding type annotations isn't enough and what it actually takes to get full value from Python's static typing ecosystem.",
        "tags": ["typing", "mypy", "annotations", "static-analysis"],
        "difficulty": "intermediate",
    },
    {
        "id": "fri-3",
        "title": "GPU Communications for Python",
        "speaker": "Benjamin Glick, Michael Yh Wang",
        "track": "AI/ML",
        "day": "Friday",
        "time": "11:00 AM",
        "room": "Room 104AB",
        "duration_minutes": 45,
        "description": "Deep dive into GPU communication primitives and how to leverage them effectively from Python for high-performance ML workloads.",
        "tags": ["gpu", "ml", "performance", "cuda"],
        "difficulty": "advanced",
    },
    {
        "id": "fri-4",
        "title": "AI-Assisted Contributions and Maintainer Load",
        "speaker": "Paolo Melchiorre",
        "track": "AI/ML",
        "day": "Friday",
        "time": "11:00 AM",
        "room": "Grand Ballroom A",
        "duration_minutes": 45,
        "description": "How AI-assisted contributions are changing open source maintainer dynamics — the good, the bad, and the practical.",
        "tags": ["ai", "open-source", "maintainers", "community"],
        "difficulty": "intermediate",
    },
    {
        "id": "fri-5",
        "title": "Container-enabled Asyncio is All You Need (to Build Pythonic AI Workflows at Scale)",
        "speaker": "Niels Bantilan",
        "track": "AI/ML",
        "day": "Friday",
        "time": "11:00 AM",
        "room": "Grand Ballroom B",
        "duration_minutes": 45,
        "description": "Using asyncio and containers to build scalable, Pythonic AI workflows without heavyweight orchestration frameworks.",
        "tags": ["asyncio", "ai", "containers", "scale"],
        "difficulty": "intermediate",
    },
    {
        "id": "fri-6",
        "title": "PEP 750 - T-strings: safer and smarter string processing",
        "speaker": "Vinícius Gubiani Ferreira",
        "track": "Core Python",
        "day": "Friday",
        "time": "11:45 AM",
        "room": "Room 103ABC",
        "duration_minutes": 30,
        "description": "An overview of PEP 750 template strings, how they improve on f-strings for safety-critical contexts like SQL and HTML.",
        "tags": ["pep", "strings", "security", "core-python"],
        "difficulty": "intermediate",
    },
    {
        "id": "fri-7",
        "title": "What's so hard about writing a type checker? A tour of ty",
        "speaker": "Carl Meyer",
        "track": "Core Python",
        "day": "Friday",
        "time": "12:30 PM",
        "room": "Room 103ABC",
        "duration_minutes": 30,
        "description": "A behind-the-scenes look at the challenges of building a Python type checker, using Astral's new 'ty' as a case study.",
        "tags": ["typing", "type-checker", "tooling", "core-python"],
        "difficulty": "advanced",
    },
    {
        "id": "fri-8",
        "title": "Making African Languages Visible: A Python-Based Guide to Low-Resource Language ID",
        "speaker": "Gift Ojeabulu",
        "track": "AI/ML",
        "day": "Friday",
        "time": "12:30 PM",
        "room": "Grand Ballroom A",
        "duration_minutes": 30,
        "description": "Using Python and NLP tools to tackle language identification for African low-resource languages, with practical open source approaches.",
        "tags": ["nlp", "ai", "diversity", "open-source"],
        "difficulty": "beginner",
    },
    {
        "id": "fri-9",
        "title": "Peeking under the hood of uv run",
        "speaker": "Zanie Blue",
        "track": "Tools",
        "day": "Friday",
        "time": "1:45 PM",
        "room": "Room 104AB",
        "duration_minutes": 30,
        "description": "A deep look at how uv run works internally — PEP 723, inline script metadata, and what makes uv the fastest Python toolchain.",
        "tags": ["uv", "packaging", "tools", "performance"],
        "difficulty": "intermediate",
    },
    {
        "id": "fri-10",
        "title": "Running Large Language Models on Laptops: Practical Quantization Techniques in Python",
        "speaker": "Aayush Kumar JVS",
        "track": "AI/ML",
        "day": "Friday",
        "time": "2:00 PM",
        "room": "Grand Ballroom A",
        "duration_minutes": 45,
        "description": "Practical guide to quantizing LLMs in Python so they fit and run fast on consumer hardware, with real benchmarks.",
        "tags": ["llm", "quantization", "ai", "performance"],
        "difficulty": "intermediate",
    },
    {
        "id": "fri-11",
        "title": "Distributing AI with Python in the Browser: Edge Inference and Flexibility Without Infrastructure",
        "speaker": "Fabio Pliger",
        "track": "AI/ML",
        "day": "Friday",
        "time": "2:45 PM",
        "room": "Grand Ballroom A",
        "duration_minutes": 45,
        "description": "Running AI inference directly in the browser using Python and WebAssembly — no server required.",
        "tags": ["ai", "wasm", "browser", "pyodide"],
        "difficulty": "intermediate",
    },
    {
        "id": "fri-12",
        "title": "pathlib: why and how to use it",
        "speaker": "Trey Hunner",
        "track": "Core Python",
        "day": "Friday",
        "time": "2:45 PM",
        "room": "Grand Ballroom B",
        "duration_minutes": 45,
        "description": "A practical guide to pathlib — why it's better than os.path, common patterns, and real-world examples.",
        "tags": ["pathlib", "stdlib", "beginner", "core-python"],
        "difficulty": "beginner",
    },
    {
        "id": "fri-13",
        "title": "Why Software Engineering Best Practices Fail in Data Engineering",
        "speaker": "Constance Martineau",
        "track": "Data Science",
        "day": "Friday",
        "time": "4:30 PM",
        "room": "Room 103ABC",
        "duration_minutes": 45,
        "description": "Why standard SWE practices like CI/CD and testing fall apart in data pipelines, and what to do instead.",
        "tags": ["data-engineering", "best-practices", "pipelines"],
        "difficulty": "intermediate",
    },
    {
        "id": "fri-14",
        "title": "Demystifying Python's Memory Management",
        "speaker": "Puneet Khushwani",
        "track": "Core Python",
        "day": "Friday",
        "time": "4:30 PM",
        "room": "Room 104AB",
        "duration_minutes": 45,
        "description": "How Python allocates and frees memory under the hood — reference counting, garbage collection, and memory profiling tools.",
        "tags": ["memory", "gc", "performance", "core-python"],
        "difficulty": "intermediate",
    },
    {
        "id": "fri-15",
        "title": "How to Build Your First Real-Time Voice Agent in Python (Without Losing Your Mind)",
        "speaker": "Camila Hinojosa Añez, Elizabeth Fuentes",
        "track": "AI/ML",
        "day": "Friday",
        "time": "5:15 PM",
        "room": "Grand Ballroom A",
        "duration_minutes": 45,
        "description": "Step-by-step guide to building a real-time voice AI agent in Python — from audio streaming to LLM integration to deployment.",
        "tags": ["ai", "voice", "agents", "streaming"],
        "difficulty": "beginner",
    },
    {
        "id": "fri-16",
        "title": "Debugging Python in Production: Practical Techniques Beyond Print Statements",
        "speaker": "Anshul Jannumahanti",
        "track": "Tools",
        "day": "Friday",
        "time": "5:15 PM",
        "room": "Room 103ABC",
        "duration_minutes": 45,
        "description": "Production debugging techniques: profilers, tracing, remote debuggers, and observability patterns that go beyond print().",
        "tags": ["debugging", "production", "observability", "tools"],
        "difficulty": "intermediate",
    },

    # ── SATURDAY MAY 16 ────────────────────────────────────────────
    {
        "id": "sat-1",
        "title": "D&I Panel: Python is for Everyone: Growing the Community Without Limits",
        "speaker": "D&I Panel",
        "track": "Keynote",
        "day": "Saturday",
        "time": "9:00 AM",
        "room": "Pacific Ballroom - Arena",
        "duration_minutes": 25,
        "description": "A panel discussion on diversity, equity, and inclusion in the Python community — growing the community without limits.",
        "tags": ["diversity", "community", "inclusion", "panel"],
        "difficulty": "all",
    },
    {
        "id": "sat-2",
        "title": "Keynote — Pablo Galindo Salgado (En Español)",
        "speaker": "Pablo Galindo Salgado",
        "track": "Keynote",
        "day": "Saturday",
        "time": "9:25 AM",
        "room": "Pacific Ballroom - Arena",
        "duration_minutes": 40,
        "description": "Saturday keynote by Python core developer Pablo Galindo Salgado, delivered in Spanish. Pablo is a CPython core developer and creator of the new 'ty' type checker.",
        "tags": ["keynote", "core-python", "charlas"],
        "difficulty": "all",
    },
    {
        "id": "sat-3",
        "title": "FastAPI Security Patterns: OAuth 2.0, JWTs, and API Keys Done Right",
        "speaker": "Ian",
        "track": "Security",
        "day": "Saturday",
        "time": "10:30 AM",
        "room": "Room 103ABC",
        "duration_minutes": 45,
        "description": "A deep dive into securing FastAPI applications with OAuth 2.0, JWT tokens, and API key patterns — with real examples of what goes wrong and how to fix it.",
        "tags": ["fastapi", "security", "oauth", "jwt", "api"],
        "difficulty": "intermediate",
    },
    {
        "id": "sat-4",
        "title": "Hash me if you can: let's talk about Python dictionaries!",
        "speaker": "Mia Bajić",
        "track": "Core Python",
        "day": "Saturday",
        "time": "10:30 AM",
        "room": "Room 104AB",
        "duration_minutes": 45,
        "description": "A deep exploration of Python's dict implementation — hashing, collision resolution, performance characteristics, and CPython internals.",
        "tags": ["dictionaries", "hashing", "internals", "core-python"],
        "difficulty": "intermediate",
    },
    {
        "id": "sat-5",
        "title": "Python for Humans - Designing Python Code Like a User Interface",
        "speaker": "Justin Lee",
        "track": "Core Python",
        "day": "Saturday",
        "time": "10:30 AM",
        "room": "Grand Ballroom A",
        "duration_minutes": 45,
        "description": "Applying UX design thinking to Python API design — how to write libraries and code that feel intuitive to humans.",
        "tags": ["api-design", "ux", "libraries", "best-practices"],
        "difficulty": "intermediate",
    },
    {
        "id": "sat-6",
        "title": "Conquer multithreaded Python with Blanket",
        "speaker": "Larry Hastings",
        "track": "Core Python",
        "day": "Saturday",
        "time": "10:30 AM",
        "room": "Grand Ballroom B",
        "duration_minutes": 45,
        "description": "Introducing Blanket — a new approach to multithreaded Python that makes concurrent code easier to write and reason about.",
        "tags": ["threading", "concurrency", "core-python", "gil"],
        "difficulty": "advanced",
    },
    {
        "id": "sat-7",
        "title": "Anatomy of a Phishing Campaign",
        "speaker": "Mike Fiedler",
        "track": "Security",
        "day": "Saturday",
        "time": "11:15 AM",
        "room": "Room 103ABC",
        "duration_minutes": 45,
        "description": "A technical breakdown of how phishing campaigns targeting Python developers and PyPI work, with defensive countermeasures.",
        "tags": ["security", "phishing", "pypi", "supply-chain"],
        "difficulty": "intermediate",
    },
    {
        "id": "sat-8",
        "title": "Don't Write Polars Code with a Pandas Accent",
        "speaker": "Joram Mutenge",
        "track": "Data Science",
        "day": "Saturday",
        "time": "11:15 AM",
        "room": "Grand Ballroom A",
        "duration_minutes": 45,
        "description": "How to write idiomatic Polars code instead of just translating Pandas patterns — unlocking the full performance of Polars.",
        "tags": ["polars", "pandas", "data", "performance"],
        "difficulty": "intermediate",
    },
    {
        "id": "sat-9",
        "title": "Zero Trust in 200ms: Implementing Identity-Per-Transaction with Python and Serverless",
        "speaker": "Tristan McKinnon",
        "track": "Security",
        "day": "Saturday",
        "time": "12:00 PM",
        "room": "Room 103ABC",
        "duration_minutes": 30,
        "description": "Building zero-trust security architectures in Python with per-transaction identity verification under tight latency budgets.",
        "tags": ["security", "zero-trust", "serverless", "identity"],
        "difficulty": "advanced",
    },
    {
        "id": "sat-10",
        "title": "No More Spreadsheets! Building PyLadiesCon Infrastructure with Python and Django",
        "speaker": "Mariatta",
        "track": "Web",
        "day": "Saturday",
        "time": "12:00 PM",
        "room": "Grand Ballroom A",
        "duration_minutes": 30,
        "description": "How the PyLadiesCon team replaced manual spreadsheets with a custom Django app to run their conference — a real-world open source project.",
        "tags": ["django", "web", "open-source", "community"],
        "difficulty": "beginner",
    },
    {
        "id": "sat-11",
        "title": "The Surprising Effectiveness of Immutable Data Structures",
        "speaker": "Brett Slatkin",
        "track": "Core Python",
        "day": "Saturday",
        "time": "1:30 PM",
        "room": "Room 104AB",
        "duration_minutes": 45,
        "description": "Why immutable data structures make Python programs simpler, safer, and easier to test — with practical patterns and examples.",
        "tags": ["immutability", "data-structures", "best-practices"],
        "difficulty": "intermediate",
    },
    {
        "id": "sat-12",
        "title": "Rust for CPython: Making Python Safer and More Robust for Everyone",
        "speaker": "Emma Smith",
        "track": "Security",
        "day": "Saturday",
        "time": "1:45 PM",
        "room": "Room 103ABC",
        "duration_minutes": 45,
        "description": "How Rust is being used to rewrite safety-critical parts of CPython, and what this means for Python's security and stability.",
        "tags": ["rust", "cpython", "security", "core-python"],
        "difficulty": "advanced",
    },
    {
        "id": "sat-13",
        "title": "Create a Python Package: From Zero to Hero",
        "speaker": "Mario Munoz",
        "track": "Tools",
        "day": "Saturday",
        "time": "1:45 PM",
        "room": "Grand Ballroom A",
        "duration_minutes": 45,
        "description": "A complete guide to creating, packaging, and publishing a Python package — from project layout to PyPI, with modern tooling.",
        "tags": ["packaging", "pypi", "uv", "beginner"],
        "difficulty": "beginner",
    },
    {
        "id": "sat-14",
        "title": "Beyond Rate Limiting: Adaptive Security for Python Web Applications",
        "speaker": "Aayush Gauba",
        "track": "Security",
        "day": "Saturday",
        "time": "2:30 PM",
        "room": "Grand Ballroom A",
        "duration_minutes": 45,
        "description": "Moving beyond simple rate limiting to adaptive, behavior-based security for Python web apps — with real implementation patterns.",
        "tags": ["security", "web", "api", "rate-limiting"],
        "difficulty": "intermediate",
    },
    {
        "id": "sat-15",
        "title": "The Terminal is the New Browser: Building Rich TUIs with Textual",
        "speaker": "Andres Pineda",
        "track": "Tools",
        "day": "Saturday",
        "time": "3:15 PM",
        "room": "Room 104AB",
        "duration_minutes": 45,
        "description": "How to build beautiful, interactive terminal UIs with Textual — the Python framework that brings app-quality UX to the command line.",
        "tags": ["tui", "textual", "cli", "tools"],
        "difficulty": "beginner",
    },
    {
        "id": "sat-16",
        "title": "Tachyon: Python 3.15's sampling profiler is faster than your code",
        "speaker": "Pablo Galindo Salgado, Laszlo Kiss Kollar",
        "track": "Core Python",
        "day": "Saturday",
        "time": "3:15 PM",
        "room": "Grand Ballroom A",
        "duration_minutes": 45,
        "description": "Introducing Tachyon, the new zero-overhead sampling profiler shipping in Python 3.15 — how it works and how to use it.",
        "tags": ["profiling", "performance", "python315", "core-python"],
        "difficulty": "intermediate",
    },
    {
        "id": "sat-17",
        "title": "The art of live process manipulation with Python 3.14's zero-overhead debugging interface",
        "speaker": "Savannah Ostrowski",
        "track": "Core Python",
        "day": "Saturday",
        "time": "3:15 PM",
        "room": "Grand Ballroom B",
        "duration_minutes": 45,
        "description": "Python 3.14 ships a new zero-overhead debugging interface — how to use it for live process inspection and production debugging.",
        "tags": ["debugging", "python314", "core-python", "production"],
        "difficulty": "advanced",
    },
    {
        "id": "sat-18",
        "title": "GitHub Actions Security in Python Packages",
        "speaker": "Andrew Nesbitt",
        "track": "Security",
        "day": "Saturday",
        "time": "4:15 PM",
        "room": "Room 103ABC",
        "duration_minutes": 45,
        "description": "Common GitHub Actions security pitfalls in Python package CI/CD, and how to harden your workflows against supply chain attacks.",
        "tags": ["security", "github-actions", "ci-cd", "supply-chain"],
        "difficulty": "intermediate",
    },
    {
        "id": "sat-19",
        "title": "Making Python Faster with Free Threading and Mypyc",
        "speaker": "Jukka Lehtosalo",
        "track": "Core Python",
        "day": "Saturday",
        "time": "4:15 PM",
        "room": "Grand Ballroom A",
        "duration_minutes": 45,
        "description": "Two paths to faster Python: free-threading (no-GIL) and Mypyc ahead-of-time compilation — practical guide to both approaches.",
        "tags": ["performance", "free-threading", "mypyc", "core-python"],
        "difficulty": "advanced",
    },
    {
        "id": "sat-20",
        "title": "Getting Started with Celery: Building Your First Background Task System in Python",
        "speaker": "Italo Carvalho Vianelli Ribeiro",
        "track": "Web",
        "day": "Saturday",
        "time": "4:15 PM",
        "room": "Grand Ballroom B",
        "duration_minutes": 45,
        "description": "A practical intro to Celery for Python developers — task queues, workers, brokers, and real-world patterns for background jobs.",
        "tags": ["celery", "async", "queues", "web"],
        "difficulty": "beginner",
    },
    {
        "id": "sat-21",
        "title": "High-Performance LLM Inference in Pure Python with PyTorch Custom Ops",
        "speaker": "Yineng Zhang",
        "track": "AI/ML",
        "day": "Saturday",
        "time": "5:00 PM",
        "room": "Grand Ballroom A",
        "duration_minutes": 45,
        "description": "Writing high-performance LLM inference kernels using PyTorch custom ops — all in pure Python, without dropping into C++.",
        "tags": ["llm", "pytorch", "performance", "ai"],
        "difficulty": "advanced",
    },
    {
        "id": "sat-22",
        "title": "Upgrading Python CLIs: From Scripts to Interactive Tools",
        "speaker": "Avik Basu",
        "track": "Tools",
        "day": "Saturday",
        "time": "5:00 PM",
        "room": "Grand Ballroom B",
        "duration_minutes": 45,
        "description": "How to evolve simple Python scripts into polished, interactive CLI tools with rich output, autocomplete, and great UX.",
        "tags": ["cli", "tools", "ux", "beginner"],
        "difficulty": "beginner",
    },

    # ── SUNDAY MAY 17 ──────────────────────────────────────────────
    {
        "id": "sun-1",
        "title": "Keynote — amanda casari",
        "speaker": "amanda casari",
        "track": "Keynote",
        "day": "Sunday",
        "time": "9:00 AM",
        "room": "Pacific Ballroom - Arena",
        "duration_minutes": 45,
        "description": "Sunday morning keynote at PyCon US 2026 by amanda casari.",
        "tags": ["keynote", "plenary"],
        "difficulty": "all",
    },
    {
        "id": "sun-2",
        "title": "Job Fair & Community Showcase",
        "speaker": "PyCon US 2026",
        "track": "Community",
        "day": "Sunday",
        "time": "9:30 AM",
        "room": "Hall AB",
        "duration_minutes": 150,
        "description": "Meet companies hiring Python developers and connect with open source community groups. Bring your resume and portfolio links!",
        "tags": ["jobs", "career", "community", "networking"],
        "difficulty": "all",
    },
    {
        "id": "sun-3",
        "title": "Learning Computer Science with Python and Music",
        "speaker": "Michael Scott Asato Cuthbert",
        "track": "Education",
        "day": "Sunday",
        "time": "1:00 PM",
        "room": "Room 103ABC",
        "duration_minutes": 45,
        "description": "Using music as a vehicle for teaching CS concepts with Python — from rhythm to recursion, a creative approach to education.",
        "tags": ["education", "music", "creative", "beginner"],
        "difficulty": "beginner",
    },
    {
        "id": "sun-4",
        "title": "From notebooks to scripts: turning one-off analysis into reusable Python code",
        "speaker": "Rafael Mendes de Jesus",
        "track": "Data Science",
        "day": "Sunday",
        "time": "1:00 PM",
        "room": "Room 104AB",
        "duration_minutes": 45,
        "description": "Practical patterns for graduating Jupyter notebooks to production-quality Python scripts and packages.",
        "tags": ["notebooks", "data-science", "refactoring", "beginner"],
        "difficulty": "beginner",
    },
    {
        "id": "sun-5",
        "title": "Leading Without Permission: Building Digital Diaspora as an Afro-Latina Woman in Tech",
        "speaker": "Veronica Rodriguez Viveros",
        "track": "Community",
        "day": "Sunday",
        "time": "1:45 PM",
        "room": "Room 103ABC",
        "duration_minutes": 30,
        "description": "A personal story about building community and leadership in tech without waiting for permission — and using Python along the way.",
        "tags": ["community", "diversity", "career", "leadership"],
        "difficulty": "all",
    },
    {
        "id": "sun-6",
        "title": "Memory management in CPython, fast or slow?",
        "speaker": "Mark Shannon",
        "track": "Core Python",
        "day": "Sunday",
        "time": "1:45 PM",
        "room": "Grand Ballroom B",
        "duration_minutes": 45,
        "description": "An authoritative look at CPython's memory management — allocators, arenas, and how memory decisions affect performance.",
        "tags": ["memory", "cpython", "performance", "core-python"],
        "difficulty": "advanced",
    },
    {
        "id": "sun-7",
        "title": "Understanding Python's logging: Combine components like Lego blocks!",
        "speaker": "nikkie",
        "track": "Core Python",
        "day": "Sunday",
        "time": "2:30 PM",
        "room": "Room 104AB",
        "duration_minutes": 45,
        "description": "A clear mental model for Python's logging module — handlers, formatters, filters, and how to compose them for any use case.",
        "tags": ["logging", "stdlib", "debugging", "beginner"],
        "difficulty": "beginner",
    },
    {
        "id": "sun-8",
        "title": "Keynote — Rachell Calhoun & Tim Schilling",
        "speaker": "Rachell Calhoun, Tim Schilling",
        "track": "Keynote",
        "day": "Sunday",
        "time": "3:15 PM",
        "room": "Pacific Ballroom - Arena",
        "duration_minutes": 45,
        "description": "Closing keynote of PyCon US 2026 by Rachell Calhoun and Tim Schilling.",
        "tags": ["keynote", "plenary", "closing"],
        "difficulty": "all",
    },
    {
        "id": "sun-9",
        "title": "Steering Council Panel",
        "speaker": "Python Steering Council",
        "track": "Keynote",
        "day": "Sunday",
        "time": "4:00 PM",
        "room": "Pacific Ballroom - Arena",
        "duration_minutes": 35,
        "description": "The Python Steering Council answers community questions and shares updates on the future direction of the Python language.",
        "tags": ["steering-council", "governance", "community", "core-python"],
        "difficulty": "all",
    },
    {
        "id": "sun-10",
        "title": "Preflight Your Data: Catch Hidden Issues Before Handoff",
        "speaker": "Jennifer Slotnick",
        "track": "Data Science",
        "day": "Saturday",
        "time": "12:00 PM",
        "room": "Room 104AB",
        "duration_minutes": 30,
        "description": "Techniques for validating and auditing data before it reaches downstream consumers — catching silent data quality issues early.",
        "tags": ["data-quality", "validation", "data-engineering"],
        "difficulty": "intermediate",
    },
    {
        "id": "fri-17",
        "title": "How to Write a Great Command Line Application",
        "speaker": "Dan Craig",
        "track": "Tools",
        "day": "Friday",
        "time": "12:30 PM",
        "room": "Grand Ballroom B",
        "duration_minutes": 30,
        "description": "Design principles and practical patterns for building CLI tools that users will actually want to use — argument parsing, UX, help text.",
        "tags": ["cli", "ux", "tools", "beginner"],
        "difficulty": "beginner",
    },
    {
        "id": "fri-18",
        "title": "Pydantic V2: Validation at the Speed of Rust (Sponsor: Pydantic)",
        "speaker": "Samuel Colvin",
        "track": "Core Python",
        "day": "Friday",
        "time": "11:30 AM",
        "room": "Room 201B",
        "duration_minutes": 30,
        "description": "Deep dive into Pydantic V2's Rust core, performance benchmarks, migration from V1, and advanced validation patterns including LLM tool calling.",
        "tags": ["pydantic", "validation", "performance", "rust"],
        "difficulty": "intermediate",
    },
]


def get_all_talks() -> list[dict]:
    return SEED_TALKS


def get_talks_by_day(day: str) -> list[dict]:
    return [t for t in SEED_TALKS if t["day"].lower() == day.lower()]


def get_talks_by_track(track: str) -> list[dict]:
    return [t for t in SEED_TALKS if t["track"].lower() == track.lower()]


def get_talk_by_id(talk_id: str) -> Optional[dict]:
    for talk in SEED_TALKS:
        if talk["id"] == talk_id:
            return talk
    return None


def search_talks(query: str) -> list[dict]:
    query_lower = query.lower()
    results = []
    for talk in SEED_TALKS:
        if (
            query_lower in talk["title"].lower()
            or query_lower in talk["description"].lower()
            or query_lower in talk["speaker"].lower()
            or any(query_lower in tag for tag in talk["tags"])
            or query_lower in talk["track"].lower()
        ):
            results.append(talk)
    return results


def format_schedule_for_llm(talks: list[dict]) -> str:
    grouped: dict[str, list] = {}
    for talk in talks:
        day = talk.get("day", "Unknown")
        if day not in grouped:
            grouped[day] = []
        grouped[day].append(talk)

    lines = []
    for day, day_talks in grouped.items():
        lines.append(f"\n### {day}")
        for t in sorted(day_talks, key=lambda x: x.get("time", "")):
            lines.append(
                f"  [{t['time']}] **{t['title']}** — {t['speaker']} | {t['track']} | {t['room']} | {t['difficulty']}"
            )
            lines.append(f"  {t['description'][:120]}...")

    return "\n".join(lines)